import { Link, useLoaderData } from 'react-router';
import ProductCard from '../components/ProductCard';

const categoryInfo = [
  ['electronics', 'Explore Tech'], ['jewelery', 'Fine Details'], ["men's clothing", "Men's"], ["women's clothing", "Women's"],
];
export default function Home() {
  const products = useLoaderData();
  const byCategory = (category) => products.find((product) => product.category === category);
  return <main>
    <section className="mx-auto max-w-[1440px] px-5 py-8 md:px-12 md:py-16"><div className="relative isolate flex min-h-[450px] items-center overflow-hidden rounded-xl bg-[#e6e8ea] px-8 md:px-16"><div className="absolute inset-y-0 right-0 w-2/3 bg-[radial-gradient(circle_at_80%_25%,#d8e2ff,transparent_22%),radial-gradient(circle_at_70%_75%,#b7c8e1,transparent_30%)]" /><div className="relative max-w-xl"><p className="mb-4 text-xs font-bold uppercase tracking-[.2em] text-[#0058be]">The curated edit</p><h1 className="text-4xl font-bold tracking-tight md:text-6xl">Elevate Your Essentials</h1><p className="mt-6 max-w-md text-lg leading-7 text-[#45464d]">Discover thoughtfully selected pieces for a modern life—minimal in look, uncompromising in quality.</p><Link to="/shop" className="mt-8 inline-block bg-[#0058be] px-8 py-4 text-xs font-bold tracking-widest text-white transition hover:bg-[#2170e4]">SHOP NOW</Link></div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-12 md:px-12 md:py-20"><div className="mb-10 flex items-end justify-between"><h2 className="text-2xl font-semibold">Featured Categories</h2><Link to="/shop" className="text-sm font-bold text-[#0058be]">View all →</Link></div><div className="grid gap-6 md:grid-cols-4">{categoryInfo.map(([category, label], i) => { const product = byCategory(category); return <Link key={category} to={`/shop?category=${encodeURIComponent(category)}`} className={`${i < 2 ? 'md:col-span-2' : ''} group relative h-72 overflow-hidden rounded-xl bg-[#e6e8ea]`}>{product && <img src={product.image} alt="" className="h-full w-full object-contain p-8 transition duration-500 group-hover:scale-110" />}<div className="absolute inset-0 bg-gradient-to-t from-[#131b2e]/80 via-transparent to-transparent" /><div className="absolute bottom-0 p-6 text-white"><h3 className="text-xl font-semibold">{category === 'jewelery' ? 'Jewelry' : category.replace("'s clothing", "’s")}</h3><span className="text-sm opacity-90">{label}</span></div></Link>; })}</div></section>
    <section className="bg-white py-12 md:py-20"><div className="mx-auto max-w-[1440px] px-5 md:px-12"><div className="mb-12 text-center"><h2 className="text-2xl font-semibold">Trending Now</h2><p className="mt-2 text-[#45464d]">Our most sought-after pieces, curated for the modern lifestyle.</p></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0, 4).map(product => <ProductCard key={product.id} product={product} />)}</div><div className="mt-12 text-center"><Link to="/shop" className="inline-block border border-[#76777d] px-8 py-3 text-xs font-bold tracking-widest hover:bg-[#f2f4f6]">VIEW ALL PRODUCTS</Link></div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-16 md:px-12 md:py-24"><div className="overflow-hidden rounded-2xl border border-[#c6c6cd] bg-[#f2f4f6] p-8 md:flex md:items-center md:justify-between md:p-16"><div className="max-w-lg"><h2 className="text-2xl font-semibold">Join the Inner Circle</h2><p className="mt-4 text-[#45464d]">Early access to new collections, exclusive deals, and curated editorial content.</p></div><form onSubmit={e => e.preventDefault()} className="mt-6 flex max-w-md gap-3 md:mt-0"><input type="email" required placeholder="Email address" className="min-w-0 flex-1 border border-[#c6c6cd] bg-white px-4 py-3 outline-none focus:border-[#0058be]" /><button className="bg-[#191c1e] px-5 text-xs font-bold tracking-wider text-white">SUBSCRIBE</button></form></div></section>
  </main>;
}
