import { Link, useLoaderData, useNavigate } from 'react-router';
import { useState } from 'react';
import { useCart } from '../context/CartContext';
import Rating from '../components/Rating';
import Icon from '../components/Icon';
const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' });
export default function ProductDetail() {
  const product = useLoaderData(); const { addItem } = useCart(); const navigate = useNavigate(); const [quantity, setQuantity] = useState(1);
  const add = () => addItem(product, quantity);
  return <main className="mx-auto max-w-[1440px] px-5 py-10 md:px-12 md:py-16"><div className="mb-8 text-xs text-[#45464d]"><Link to="/shop" className="hover:text-[#0058be]">Shop All</Link> <span className="mx-2">/</span><span className="capitalize">{product.category}</span></div><section className="grid gap-10 md:grid-cols-2 md:gap-16"><div><div className="aspect-square rounded-lg border border-[#c6c6cd] bg-white p-12"><img src={product.image} alt={product.title} className="h-full w-full object-contain" /></div><div className="mt-4 grid grid-cols-4 gap-3"><div className="aspect-square border-2 border-[#0058be] bg-white p-3"><img src={product.image} alt="" className="h-full w-full object-contain" /></div>{[1,2,3].map(i => <div key={i} className="aspect-square border border-[#c6c6cd] bg-[#f2f4f6]" />)}</div></div><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0058be]">{product.category}</p><h1 className="mt-3 text-3xl font-bold tracking-tight md:text-5xl">{product.title}</h1><div className="mt-5"><Rating rating={product.rating} /></div><p className="mt-6 text-2xl font-semibold">{money.format(product.price)}</p><p className="mt-7 leading-7 text-[#45464d]">{product.description}</p><ul className="mt-6 space-y-2 text-sm text-[#45464d]"><li className="flex gap-2"><Icon className="text-[#0058be]">check</Icon>Thoughtfully selected quality</li><li className="flex gap-2"><Icon className="text-[#0058be]">check</Icon>Free standard shipping over $50</li><li className="flex gap-2"><Icon className="text-[#0058be]">check</Icon>Easy 30-day returns</li></ul><hr className="my-8 border-[#c6c6cd]" /><div className="flex flex-col gap-4 sm:flex-row"><div className="flex h-12 w-32 items-center border border-[#c6c6cd]"><button onClick={() => setQuantity(q => Math.max(1, q - 1))} className="grid h-full flex-1 place-items-center hover:bg-[#f2f4f6]"><Icon>remove</Icon></button><span className="w-10 text-center">{quantity}</span><button onClick={() => setQuantity(q => q + 1)} className="grid h-full flex-1 place-items-center hover:bg-[#f2f4f6]"><Icon>add</Icon></button></div><button onClick={add} className="flex h-12 flex-1 items-center justify-center gap-2 border border-[#191c1e] text-xs font-bold tracking-wider transition hover:bg-[#f2f4f6]"><Icon>shopping_cart</Icon>ADD TO CART</button><button onClick={() => { add(); navigate('/cart'); }} className="h-12 flex-1 bg-[#0058be] text-xs font-bold tracking-wider text-white transition hover:bg-[#2170e4]">BUY NOW</button></div><div className="mt-6 flex items-center gap-2 rounded bg-[#f2f4f6] p-4 text-sm text-[#45464d]"><Icon>local_shipping</Icon>Free standard shipping on orders over $50. Ships within 24 hours.</div></div></section></main>;
}
