import { useLoaderData, useSearchParams } from 'react-router';
import { useMemo, useState } from 'react';
import ProductCard from '../components/ProductCard';

export default function Shop() {
  const products = useLoaderData(); const [params, setParams] = useSearchParams(); const [min, setMin] = useState(''); const [max, setMax] = useState('');
  const category = params.get('category') || ''; const term = params.get('q') || ''; const sort = params.get('sort') || 'featured';
  const visible = useMemo(() => products.filter(p => (!category || p.category === category) && (!term || p.title.toLowerCase().includes(term.toLowerCase())) && (!min || p.price >= Number(min)) && (!max || p.price <= Number(max))).sort((a, b) => sort === 'price-asc' ? a.price - b.price : sort === 'price-desc' ? b.price - a.price : sort === 'rating' ? b.rating.rate - a.rating.rate : 0), [products, category, term, min, max, sort]);
  const changeCategory = (value) => { const next = new URLSearchParams(params); value ? next.set('category', value) : next.delete('category'); setParams(next); };
  return <main className="mx-auto flex max-w-[1440px] flex-col gap-8 px-5 py-10 md:flex-row md:px-12 md:py-14"><aside className="w-full shrink-0 md:w-60"><div className="sticky top-28 space-y-7"><div><h1 className="text-2xl font-semibold">Shop all</h1><p className="mt-1 text-sm text-[#45464d]">Find your next essential.</p></div><div className="border-y border-[#c6c6cd] py-6"><p className="mb-3 text-xs font-bold tracking-widest">CATEGORY</p>{['electronics','jewelery',"men's clothing","women's clothing"].map(item => <label key={item} className="mb-2 flex cursor-pointer items-center gap-3 text-sm capitalize text-[#45464d]"><input type="radio" checked={category === item} onChange={() => changeCategory(item)} name="category" className="accent-[#0058be]" />{item}</label>)}<button onClick={() => changeCategory('')} className="mt-3 text-xs font-bold text-[#0058be]">CLEAR CATEGORY</button></div><div><p className="mb-3 text-xs font-bold tracking-widest">PRICE RANGE</p><div className="flex gap-2"><input value={min} onChange={e => setMin(e.target.value)} type="number" placeholder="Min" className="w-1/2 border border-[#c6c6cd] bg-transparent px-3 py-2 text-sm outline-none focus:border-[#0058be]" /><input value={max} onChange={e => setMax(e.target.value)} type="number" placeholder="Max" className="w-1/2 border border-[#c6c6cd] bg-transparent px-3 py-2 text-sm outline-none focus:border-[#0058be]" /></div></div></div></aside><section className="min-w-0 flex-1"><div className="mb-6 flex flex-wrap items-center justify-between gap-4 border-b border-[#c6c6cd] pb-4"><p className="text-sm text-[#45464d]">Showing <strong className="text-[#191c1e]">{visible.length}</strong> results{term && <> for “{term}”</>}</p><label className="text-xs font-bold tracking-wider">SORT BY <select value={sort} onChange={e => { const next = new URLSearchParams(params); next.set('sort', e.target.value); setParams(next); }} className="ml-2 border border-[#c6c6cd] bg-transparent px-3 py-2 text-sm font-normal outline-none"><option value="featured">Featured</option><option value="price-asc">Price: Low to High</option><option value="price-desc">Price: High to Low</option><option value="rating">Best Rating</option></select></label></div>{visible.length ? <div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-3">{visible.map(product => <ProductCard key={product.id} product={product} />)}</div> : <p className="rounded-lg bg-white p-10 text-center text-[#45464d]">No products match those filters.</p>}</section></main>;
}
